<a href="https://colab.research.google.com/github/aayeshaqureshi/nlp/blob/main/word_embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install tensorflow-gpu 

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 588.3 MB 6.6 kB/s 
     |████████████████████████████████| 1.7 MB 54.4 MB/s 
     |████████████████████████████████| 439 kB 54.2 MB/s 
     |████████████████████████████████| 6.0 MB 48.8 MB/s 
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.9.0
    Uninstalling tensorflow-estimator-2.9.0:
      Successfully uninstalled tensorflow-estimator-2.9.0
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.9.1
    Uninstalling tensorboard-2.9.1:
      Successfully uninstalled tensorboard-2.9.1
  Attempting uninstall: keras
    Found existing installation: keras 2.9.0
    Uninstalling keras-2.9.0:
      Successfully uninstalled keras-2.9.0
  Attempting uninstall: flatbuffers
    Found existing installation: flatbuffers 1.12
    Uninstalling flatbuffers-1.12:
      Successfully 

In [ ]:
#lets import tesnorflow and check the version 
import tensorflow as tf 
print(tf.__version__)

2.11.0


ONE HOT IS A LIBRARY IN TENSOR FLOW TO PERFORM ONE HOT ENCODING

In [ ]:
from tensorflow.keras.preprocessing.text import one_hot 

In [ ]:
#sentences are given. our aim is to convert these sentences into some form of vectors
sentence= ['the glass of milk',
           'the glass of juice',
           'the cup of tea',
           'I am a good boy',
           'I am a good developer',
           'understand the meaning of words',
           'your videos are good',
    
]

In [ ]:
sentence

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

# We are going to use one hot encoding to convert the words and then we convert these into vectors using embedding layers


In [ ]:
# we are gonna take vocab size as 10000 for training the words

In [ ]:
voc_size = 10000

# ONE HOT ENCODING
We have our own data so we use OHE

In [ ]:
#words and voc size is given in the parameters
#this will give us the one hot rep for each word
#for each word there will be index one where it is found
#we get the index number where the word is 1 or present

In [ ]:
onehot_repr= [one_hot(words, voc_size) for words in sentence]
print(onehot_repr)
#every square bracket is a sentence
#there is the word the in index 4206

[[4206, 2550, 8607, 951], [4206, 2550, 8607, 207], [4206, 271, 8607, 4157], [7344, 669, 7931, 7549, 1392], [7344, 669, 7931, 7549, 1963], [8818, 4206, 7966, 8607, 2985], [5476, 8593, 8992, 7549]]


## WORD EMBEDDING REPRESENTATION

In [ ]:
#we install some of the libraries such as embeddig
# pad sequences is used for pre and post padding
#sequential
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from  tensorflow.keras.models import Sequential

In [ ]:
import numpy as np

In [ ]:
#assigning max sentence length as 8
sent_length=8
#pad sequnces is going to make all vectors of 8 size- for uniformity 
# the first one has 4 indexes so we add 4 more zeroes
#if there are 5 indexes we will add 3 more zeroes


the problem we were facing here was that our input size is not fied so we made sure to fix the input size using padding 


In [ ]:
embedded_docs=pad_sequences(onehot_repr, padding='pre',maxlen= sent_length)
#if u set padding front then it sets it to zeroes before
#if u set padding to post it sets it to zeroes after

In [ ]:
print(embedded_docs)

[[   0    0    0    0 4206 2550 8607  951]
 [   0    0    0    0 4206 2550 8607  207]
 [   0    0    0    0 4206  271 8607 4157]
 [   0    0    0 7344  669 7931 7549 1392]
 [   0    0    0 7344  669 7931 7549 1963]
 [   0    0    0 8818 4206 7966 8607 2985]
 [   0    0    0    0 5476 8593 8992 7549]]


## we convert each and every feature into vectors
vectors - eacha nd every features has its own features further 

In [ ]:
#feature representation dimensions is 10
#set feature rep dimensions as 10
dim=10

## CREATE A SEQUENTIAL MODEL

In [ ]:
model= Sequential()
#parameters: 1. is voc_size we took it as 10000
#2. how many features u want for each vector 
#3. specify the input length
model.add(Embedding(voc_size, 10, input_length= sent_length))

In [ ]:
#we are using adam optimzer and mean square error
model.compile('adam','mse')

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [ ]:
#checking for the first sentence- glass of milk
embedded_docs[0]

array([   0,    0,    0,    0, 4206, 2550, 8607,  951], dtype=int32)

In [ ]:
#if you want to see the feature representation of this model we use predict of embedded docs
model.predict(embedded_docs[0])

#each feature is represented by 10 feature dimensions


1/1 [==============================] - 1s 553ms/step


array([[ 0.03218989, -0.00977363,  0.03190937, -0.01127303, -0.01274774,
         0.04836253, -0.04956652, -0.04022051,  0.01312622,  0.02887647],
       [ 0.03218989, -0.00977363,  0.03190937, -0.01127303, -0.01274774,
         0.04836253, -0.04956652, -0.04022051,  0.01312622,  0.02887647],
       [ 0.03218989, -0.00977363,  0.03190937, -0.01127303, -0.01274774,
         0.04836253, -0.04956652, -0.04022051,  0.01312622,  0.02887647],
       [ 0.03218989, -0.00977363,  0.03190937, -0.01127303, -0.01274774,
         0.04836253, -0.04956652, -0.04022051,  0.01312622,  0.02887647],
       [ 0.03841702, -0.01727964, -0.01489743,  0.03985192,  0.0490088 ,
        -0.02620417, -0.00596821,  0.00476018, -0.00926703, -0.00336843],
       [-0.03500042, -0.00101609, -0.03817726,  0.03503856,  0.02806768,
        -0.00768336, -0.03772421, -0.02176092,  0.04957275, -0.03060021],
       [ 0.04075053, -0.02808684,  0.04888676, -0.00968386,  0.02162239,
        -0.02189831, -0.00913107, -0.01450526

In [ ]:
#if you want to do it for all the sentences 
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 44ms/step
[[[ 0.03218989 -0.00977363  0.03190937 -0.01127303 -0.01274774
    0.04836253 -0.04956652 -0.04022051  0.01312622  0.02887647]
  [ 0.03218989 -0.00977363  0.03190937 -0.01127303 -0.01274774
    0.04836253 -0.04956652 -0.04022051  0.01312622  0.02887647]
  [ 0.03218989 -0.00977363  0.03190937 -0.01127303 -0.01274774
    0.04836253 -0.04956652 -0.04022051  0.01312622  0.02887647]
  [ 0.03218989 -0.00977363  0.03190937 -0.01127303 -0.01274774
    0.04836253 -0.04956652 -0.04022051  0.01312622  0.02887647]
  [ 0.03841702 -0.01727964 -0.01489743  0.03985192  0.0490088
   -0.02620417 -0.00596821  0.00476018 -0.00926703 -0.00336843]
  [-0.03500042 -0.00101609 -0.03817726  0.03503856  0.02806768
   -0.00768336 -0.03772421 -0.02176092  0.04957275 -0.03060021]
  [ 0.04075053 -0.02808684  0.04888676 -0.00968386  0.02162239
   -0.02189831 -0.00913107 -0.01450526  0.01849696  0.02291114]
  [-0.00170984  0.0102702  -0.01259585 -0.04743252  0.042045

In [ ]:
sent1=['the world is a better place',
      'marvel series is my fav movie',
      'I like DC movies',
      'the cat is eating the food',
      'tom and jerry is my favourite movie',
      'python is my fav programming language'
    
]

In [ ]:
vocab_size=500

### 1. ONE HOT ENCODING 

In [ ]:
onehot_reprs= [one_hot(words, voc_size) for words in sent1]
print(onehot_reprs)


[[124, 30, 455, 266, 98, 46], [21, 460, 455, 477, 66, 370], [151, 492, 105, 200], [124, 418, 455, 449, 124, 313], [26, 222, 12, 455, 477, 315, 370], [192, 455, 477, 66, 472, 115]]


### 2. WORD EMBEDDING

In [ ]:
sentence_length=10

In [ ]:
embedded_docs=pad_sequences(onehot_reprs, padding='post',maxlen= sentence_length)

In [ ]:
print(embedded_docs)

[[124  30 455 266  98  46   0   0   0   0]
 [ 21 460 455 477  66 370   0   0   0   0]
 [151 492 105 200   0   0   0   0   0   0]
 [124 418 455 449 124 313   0   0   0   0]
 [ 26 222  12 455 477 315 370   0   0   0]
 [192 455 477  66 472 115   0   0   0   0]]


### 3. CREATE A SEQUENTIAL MODEL

In [ ]:
dim=10
model= Sequential()
model.add(Embedding(vocab_size, 10, input_length= sentence_length))


In [ ]:
model.compile('adam','mse')

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 10, 10)            5000      
                                                                 
Total params: 5,000
Trainable params: 5,000
Non-trainable params: 0
_________________________________________________________________


In [ ]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 46ms/step
[[[-1.63179636e-03  2.76004784e-02 -6.06377050e-03 -4.85909693e-02
   -3.46118324e-02  3.19949426e-02 -7.28833675e-03  1.44860893e-03
    2.60118507e-02  3.30248140e-02]
  [ 2.39403732e-02 -1.10663474e-04  1.97241418e-02  4.27784771e-03
    3.50763239e-02 -1.47997215e-03 -2.51560099e-02 -4.36683744e-03
   -3.85417715e-02  6.56636804e-03]
  [-1.63247585e-02  3.14583629e-03 -4.69005108e-03  2.09174789e-02
    3.06092165e-02 -2.04161890e-02  2.94783004e-02 -3.10891159e-02
    1.42978318e-02  4.08987664e-02]
  [ 2.67292894e-02 -1.06962770e-03 -2.98388731e-02 -3.76718268e-02
   -1.29605159e-02 -4.80149277e-02 -4.62107658e-02 -3.87960188e-02
   -2.15676669e-02 -2.19223648e-03]
  [-2.73064617e-02  2.88496353e-02 -2.99893320e-04  3.77072208e-02
    3.44230793e-02  9.33873653e-03  3.71257104e-02 -1.01585016e-02
   -2.10351869e-03  4.21457179e-02]
  [ 1.69066302e-02  3.91832925e-02 -3.14971209e-02 -2.65794881e-02
   -1.74515322e-03  3.74346860e